add -f flag for install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,8 +8,25 @@ DOTBOT_DIR="dotbot"
 DOTBOT_BIN="bin/dotbot"
 BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
+while getopts ":f" opt; do
+  case $opt in
+    f)
+      FORCE=0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
+
 cd "${BASEDIR}"
 git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
 git submodule update --init --recursive "${DOTBOT_DIR}"
 
-"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
+if [ $FORCE ]
+then
+    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"
+else
+    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
+         -d "${BASEDIR}" -c <(sed 's/force: true//' "${CONFIG}")
+fi
